### ISSUE TITLE
Tagging script incorrectly resolves location

### ISSUE THREAD

**Issue by PeterShipstoneAND** [DFE-Digital/terraform-azurerm-container-apps-hosting#191]
The script is incorrectly resolving the [azure location](https://azuretracks.com/2021/04/current-azure-region-names-reference/), it's using the **display name** (e.g. West Europe) instead of using the **name** (e.g. westeurope).  This means when the script builds the MC_RESOURCE_GROUP_NAME it is invalid.

Execution Error:
![image](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/assets/132479391/ef72793d-8950-4323-887d-09f99878ac74)

Code responsible for getting location:
![image](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/assets/132479391/cd18fa1e-91ce-4de5-81b9-6aa2c779928b)

Azure resource getails:
![image](https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/assets/132479391/865b620a-328a-441a-8b53-08b0ec452ade)

**Comment by Stretch96** [comment]
Thanks for raising this

It's interesting that this has only recently surfaced as a bug - I wonder if the api response changed to be the display name rather than the name

In any case, we can fix this by changing the display name to lower case and removing the spaces which seems a safe way to do this at the moment

**Comment by Stretch96** [comment]
https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/pull/192
