### ISSUE TITLE
Cache rules cause problematic behaviour for users

### ISSUE THREAD

**Issue by DrizzlyOwl** [DFE-Digital/terraform-azurerm-container-apps-hosting#46]
https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/blob/8a3e2b16981b7f47643f4aeba38db428d1783306/cdn.tf#L76-L81

Having these cache rules deployed by default causes issues with dynamic applications that rely on user sessions.

**Proposal**
- Add a new variable for enabling/disabling caching
- (nice to have) Allow an option for overriding the default `query_strings`

[Slack discussion](https://ukgovernmentdfe.slack.com/archives/C04DR5UDT5H/p1670426949823169)

**Comment by Stretch96** [comment]
These are the defaults for a CDN route, defined in the Terraform docs - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_route

I _think_ that Azure CDN should respect the response Cache-Control header, and sholudn't cache 4xx, 5xx by default

The `cache` block referenced (the example set within Terraform docs) only appears to force cache rules based on Query Strings - however the `IgnoreSpecifiedQueryStrings` may be causing Azure CDN to cache everything but the `query_strings` list

We could try remove the `cache` block completely

I've been trying to find some documentation around the cache behaviiour of Azure CDN, but so far have only got some generic information rather than technical documentation - https://learn.microsoft.com/en-us/azure/cdn/cdn-how-caching-works

**Comment by DrizzlyOwl** [comment]
>the IgnoreSpecifiedQueryStrings may be causing Azure CDN to cache everything but the query_strings list

Certainly seemed to be the case according to @mec

**Comment by Stretch96** [comment]
I've tested that removing the `cache` block does indeed disable caching

I'll open a PR for it, and then we can consider adding a feature to conditionally add cache settings

**Comment by Stretch96** [comment]
A fix has been merged in for this now:
https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/pull/47
